--- #YAML:1.0
name:               Date-Holidays-AU
version:            0.09
abstract:           Determine Australian Public Holidays
author:
    - David Dick <ddick@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:          0
    Date::Easter:  0
    Test::More:    0
    Time::Local:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
