--- #YAML:1.0
name:                Date-Holidays-AU
version:             0.08
abstract:            Determine Australian Public Holidays
license:             perl
author:              
    - David Dick <ddick@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Date::Easter:                  0
    Test::More:                    0
    Time::Local:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
